
version: "3.9"
services:
  app:
    container_name: nodeapp
    build: ./app
    image: rrose666/eng84_sparta_app:v1
    depends_on:
      - database
    environment:
      DB_HOST: mongodb://mongodb:27017/posts
    ports:
      - 3000:3000

  database:
    image: mongo
    restart: always
    container_name: mongodb
    image: mongo
    # build: ./mongod
    ports: 
      - "27017:27017"
