
# version: "3.9"
# services:
#   app:
#     container_name: nodeapp
#     build: ./app
#     #image: rrose666/eng84_sparta_app:v1
#     depends_on:
#       - mongodb
#     environment:
#       DB_HOST: mongodb://mongodb:27017/posts
#     ports:
#       - 3000:3000

#   mongodb:
#     image: mongo
#     restart: always
#     container_name: mongod
#     image: mongo
#     build: ./mongod
#     ports: 
#       - "27017:27017"



version: "3"

services:
  mongo:
    container_name: mongo
    build: ./db
    volumes:
      - ./db/data:/data
    ports:
      - "27017:27017"

  app:
    container_name: app
    build: ./app
    environment:
      - DB_HOST=mongodb://mongo:27017/posts
    ports:
      - "3000:3000"
    volumes:
      - ./app/data:/data
    depends_on: 
      - mongo